const PRODUCTS =[
    {
        id: 1,
        name: 'Bluetooth  & WireLess Over-Ear HeadPhones(Black)',
        price: '$12',
        images: require('./images/1.jpg'),
        details: 'hfhuwr , jjfiojie a s dff fg  d  gfhjwhnf fhhf jjh perijirmfno jnksndkn jnfjcndjn jdnfjdnjkn',
    },
    {
        id: 2,
        name: 'Apple iphone 128GB',
        price: '$123',
        images: require('./images/2.jpg'),
        details: 'hfhuwr , jjfiojie a s dff fg  d  gfhjwhnf fhhf jjh perijirmfno jnksndkn jnfjcndjn jdnfjdnjkn',
    },
    {
        id: 3,
        name: 'Running Shoe Red & White',
        price: '$14',
        images: require('./images/3.jpg'),
        details: 'hfhuwr , jjfiojie a s dff fg  d  gfhjwhnf fhhf jjh perijirmfno jnksndkn jnfjcndjn jdnfjdnjkn',
    },
    {
        id: 4,
        name: 'Apple iphone blue 64GB',
        price: '$189',
        images: require('./images/4.jpg'),
        details: 'hfhuwr , jjfiojie a s dff fg  d  gfhjwhnf fhhf jjh perijirmfno jnksndkn jnfjcndjn jdnfjdnjkn',
    },
    {
        id: 5,
        name: 'Bluetooth  & WireLess Over-Ear HeadPhones(Black)',
        price: '$124',
        images: require('./images/5.jpg'),
        details: 'hfhuwr , jjfiojie a s dff fg  d  gfhjwhnf fhhf jjh perijirmfno jnksndkn jnfjcndjn jdnfjdnjkn',
    },
    {
        id: 6,
        name: 'Bluetooth  & WireLess Over-Ear HeadPhones(Black)',
        price: '$12',
        images: require('./images/6.jpg'),
        details: 'hfhuwr , jjfiojie a s dff fg  d  gfhjwhnf fhhf jjh perijirmfno jnksndkn jnfjcndjn jdnfjdnjkn',
    },
    {
        id: 7,
        name: 'Bluetooth  & WireLess Over-Ear HeadPhones(Black)',
        price: '$12',
        images: require('./images/7.jpg'),
        details: 'hfhuwr , jjfiojie a s dff fg  d  gfhjwhnf fhhf jjh perijirmfno jnksndkn jnfjcndjn jdnfjdnjkn',
    },
    {
        id: 8,
        name: 'Bluetooth  & WireLess Over-Ear HeadPhones(Black)',
        price: '$12',
        images: require('./images/8.jpg'),
        details: 'hfhuwr , jjfiojie a s dff fg  d  gfhjwhnf fhhf jjh perijirmfno jnksndkn jnfjcndjn jdnfjdnjkn',
    },
    {
        id: 9,
        name: 'Bluetooth  & WireLess Over-Ear HeadPhones(Black)',
        price: '$12',
        images: require('./images/9.jpg'),
        details: 'hfhuwr , jjfiojie a s dff fg  d  gfhjwhnf fhhf jjh perijirmfno jnksndkn jnfjcndjn jdnfjdnjkn',
    },
    {
        id: 10,
        name: 'Bluetooth  & WireLess Over-Ear HeadPhones(Black)',
        price: '$12',
        images: require('./images/10.jpg'),
        details: 'hfhuwr , jjfiojie a s dff fg  d  gfhjwhnf fhhf jjh perijirmfno jnksndkn jnfjcndjn jdnfjdnjkn',
    },
    {
        id: 11,
        name: 'Bluetooth  & WireLess Over-Ear HeadPhones(Black)',
        price: '$12',
        images: require('./images/11.jpg'),
        details: 'hfhuwr , jjfiojie a s dff fg  d  gfhjwhnf fhhf jjh perijirmfno jnksndkn jnfjcndjn jdnfjdnjkn',
    },
    {
        id: 12,
        name: 'Bluetooth  & WireLess Over-Ear HeadPhones(Black)',
        price: '$12',
        images: require('./images/12.jpg'),
        details: 'hfhuwr , jjfiojie a s dff fg  d  gfhjwhnf fhhf jjh perijirmfno jnksndkn jnfjcndjn jdnfjdnjkn',
    },
    {
        id: 13,
        name: 'Red & Black Gaming Mouse for PC',
        price: '$12',
        images: require('./images/13.jpg'),
        details: 'hfhuwr , jjfiojie a s dff fg  d  gfhjwhnf fhhf jjh perijirmfno jnksndkn jnfjcndjn jdnfjdnjkn',
    },
    {
        id: 14,
        name: 'MultiPurpose College Bag Bagpack',
        price: '$12',
        images: require('./images/14.jpg'),
        details: 'hfhuwr , jjfiojie a s dff fg  d  gfhjwhnf fhhf jjh perijirmfno jnksndkn jnfjcndjn jdnfjdnjkn',
    },
    {
        id: 15,
        name: 'White & Black Watch Concept',
        price: '$12',
        images: require('./images/15.jpg'),
        details: 'hfhuwr , jjfiojie a s dff fg  d  gfhjwhnf fhhf jjh perijirmfno jnksndkn jnfjcndjn jdnfjdnjkn',
    },
    
]

export default PRODUCTS;